version: '3.7'

services:

  rtsp-relay:
    build: .
    image: flaviostutz/rtsp-relay
    ports: 
      - 8554:8554
      - 9000:8000
      - 9001:8001
    restart: always
    environment:
        - SOURCE_URL=http://ip-thomasmarina.greatlakescam.com/user/cgi-bin/getstream.cgi?10&&&&0&0&0&0&0
